version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      pip3 install -r requirements-dev.txt
  build:
    commands:
      - make test
      - make build

reports:
  pytest_reports:
    files:
      - testreport.xml
    base-directory: .
    file-format: JUNITXML