version: 0.2

env:
  parameter-store:
    FOO: "/api/env"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      pip3 install -r requirements-dev.txt
  build:
    commands:
      - echo ${FOO}      
